### PR TITLE
BTA-1674-Add-Ability-In-Our-SDK-To-Parse-And-Validate-Webhook-Headers-Java

### PR DESCRIPTION
**Pull request by linniethepooh**
Added headers and url to the webhook content example and made used of the
`validateWebhookRequest` method (see link below )which validates the webhook headers before
allowing them to be parsed.

Link: https://github.com/bitpesa/bitpesa-api-specification/pull/109

### CODE REVIEW

**Comment by sztupy** [comment]
Please see the comments on https://github.com/bitpesa/bitpesa-sdk-java7/pull/4

**Comment by linniethepooh** [comment]
@sztupy changes made

**Comment by sztupy** [comment]
Please still add the examples. See for example https://github.com/bitpesa/bitpesa-sdk-javascript/commit/9a07267954cfd7083930ee80972611ef0d4b74e3 or https://github.com/bitpesa/bitpesa-sdk-dotnet/commit/673009c48f1f20dcb33cd7c0b9116d86a989c4c0

**Comment by linniethepooh** [comment]
@sztupy comments added

**Review by sztupy — APPROVED** [review]

**Pull request merged**
